server:
  port: 7002
spring:
 dubbo:
  application:
   name: consumer
  registry:
   address: zookeeper://127.0.0.1:2181 # Zookeeper 注册中心
  protocol:
   name: dubbo
   port: 20880
  scan: com.dubbo.test
