server:
  port: 7001
spring:
 dubbo:
  application:
   name: provider
  registry:
   address: zookeeper://127.0.0.1:2181;zookeeper://127.0.0.1:2182;zookeeper://127.0.0.1:2183
  protocol:
   name: dubbo
   port: 20880
  scan: com.test.dubbo.com.wh.service.impl.*

